ResultadosDigitais/matrix

office.server.js
public/office.web.js

Neste PR adicionei a funcionalidade do usuário entrar automaticamente na última sala quando ele fizer login ou dar refresh. O histórico é ligado ao id do usuário, o que permite várias contas no mesmo navegador terem seu histórico de última sala salvos independente.

Entrar na última sala quando o usuário acessar a app ou dar refresh

---

.github/ISSUE_TEMPLATE.md

Create first version of issue template

Create issue template v1

---

app.server.js
package-lock.json
package.json
views/index.ejs

enable bootstrap

---

.github/ISSUE_TEMPLATE/enhancement_template.md
.github/ISSUE_TEMPLATE/feature_template.md
.github/ISSUE_TEMPLATE/issue_template.md

I'm creating a new enhancement template. Now, the contributor will can choose which kind of issue he wants: enhancement or issue

Create enhancement request template

---

controllers/office.controller.js
public/css/office.css
public/office.web.js
public/profile.web.js
views/office.ejs

Adds Navabar.
Add logout button

Add Logout Button

---

README.md
SETUP.md

Minor changes to organize setup instructions from the main readme

Docs for env setup

---

.circleci/config.yml
.editorconfig
.eslintrc.js
app.server.js
controllers/google.credentials.controller.js
controllers/office.controller.js
office.server.js
package.json
public/index.web.js
public/office.web.js
public/profile.web.js
test/app.server.test.js
test/controllers/google.credentials.controller.test.js
test/controllers/office.controller.test.js
test/public/profile.web.test.js

This PR adds eslint and also runs autofix ( `eslint --fix './**/*.js' `)

Add eslint and auto fix

---

public/office.web.js
views/office.ejs

add bootstrap layout in room

---

public/office.web.js
views/office.ejs

this is an experiment I'm trying to embed video and audio using jitsi.org. before approve this PR please test in your local environment.

add integration with jitsi.org

---

file/default.room.web.json
public/css/office.css
public/office.web.js
views/office.ejs

Fix some layout bugs
- Spacing between users.
- Modal meeting title.
- Rooms disposition
close: https://github.com/juliemar/matrix/issues/75

Fix office room layout

---

app.server.js
file/default.room.web.json
office.server.js
public/office.web.js

related: https://github.com/juliemar/matrix/issues/77

set as default room the first room of the room list

---

public/css/office.css
public/js/office.web.js
views/office.ejs

User in room style

---

public/js/office.web.js

Only apply style for the current user.

Fix user in room

---

views/index.ejs

This Pull Request fixes issue https://github.com/ResultadosDigitais/matrix/issues/89

Add a h-100 class to fix the height screen 100% issue

---

public/js/office.web.js

Show in the notification the name of the room.

Inform what room the user has been entered

---

.babelrc
.circleci/config.yml
Dockerfile
app.server.js
controllers/google.credentials.controller.js
controllers/office.controller.js
office.server.js
package-lock.json
package.json
test/controllers/google.credentials.controller.test.js
test/controllers/office.controller.test.js

This PR do some refactor to all .js files translating to the newest version of JavaScript.
This PR update the nodejs to the 10.15.3 (LTS) and introduces babel to use import syntax.

Use JavaScript next syntax

---

public/js/office.web.js
views/office.ejs

Enable user to logout

---

test/controllers/office.controller.test.js

refactoring office controller test and add a new test about isMeet flag

refactoring office controller test and add a new test about isMeet flag

---

.eslintrc.js
controllers/google.credentials.controller.js
controllers/office.controller.js
package-lock.json
package.json
public/js/index.web.js
public/js/profile.web.js
test/controllers/google.credentials.controller.test.js
test/controllers/office.controller.test.js
test/public/profile.web.test.js

In this PR I'm fixing ESLint config to enable VSCode editor to verify errors during development.
I'm also fixing some eslint erros in some files.
We need to fix eslint in the following files as well:

ESLint config and fixes

---

README.md
app.json

Closes https://github.com/ResultadosDigitais/matrix/issues/68

Add deploy to heroku manifest

---

office.server.js
package-lock.json
public/js/office.events.web.js
public/js/office.web.js
public/js/profile.web.js
views/office.ejs

This PR main intent is to:
- Remove the use of `var` to use `let` and `const` instead
- Minor fixes
Also, I fixed a lot of eslint warning (except in the `office.web.js`, I think is best to do it in a separated PR, to make the review easier)
:warning: Before ship it, it's important to validate the whole flow (login/logout, enter/leave rooms).

Minor code fixes

---

file/default.room.web.json

Given that the project is using jitsi, the room external meet url is unnecessary and may be removed.

Remove unnecessary external url from rooms

---

package-lock.json
package.json

**WTF**
This PR configures code coverage report. 
run `npm test`  and you will receive the code coverage result. **Ohh** we have a lot of work :)

add code coverage repport

---

app.server.js
controllers/rooms.controller.js
test/app.server.test.js

Refactor rooms strategy to allow different ways to fetch rooms data.

Refactor rooms strategy

---

public/css/header.css
public/css/office.css
public/js/header.js
public/js/office.web.js
views/header.ejs
views/office.ejs

This PR improve matrix menu UX, doing:
1. Fixed menu (We can scroll between all rooms and always see the menu to perform a logout or any other action).
2. Logout moved to a menu dropbox. (One way of add more funcionality and keep dashboard screen simple).
3. Refactor menu component code to decouple code.

Improve matrix menu UX

---

package-lock.json
package.json

When installing the project with `npm install` I noticed that there was a vulnerability issue, then I used `npm audit fix` to fix it.
Also, after installing the project dependencies some versions changed on `package-lock.json` so I'm updating them as well.
By the way, nice project!

Fix vulnerability issue and update package-lock

---

package-lock.json
public/js/header.js

This PR returns the "Wats'up surname" in the matrix header 
Logged in #matrix in the header today appear only "surname", the last version had "Whats'up surname" this message is funny comparing with only "surname"

returning message whats'up surname in the header

---

public/js/office.web.js

Clean up file `public/js/office.web.js` by:
- Removing not used parameter from a function
- Improving functions readability by using ES6 syntax
- Removing unnecessary `else` from function
- Removing not used/duplicated/mistyped function
- And, removing a not used variable from a function
> I suggest reviewing commit-by-commit.

Office web clean up

---

test/controllers/office.controller.test.js

some liner of office.controller.js needs code coverage   
run `npm test`
the report of office.controller.js code coverage now is 100%

improve to 100% office.controller.js code coverage

---

public/js/office.web.js
views/office.ejs

Fix #123
- Run project locally `docker-compose up`
- Log and enter into a room
- Click outside the modal
- Click on the `x` button
Hey, @amandarover could you please review it?

Avoid close meet modal by mistake

---

public/js/office.web.js

How can I test this PR.
1) you have to be logged with 2 users in different rooms
2) Logged with "user B", execute right click on "user A".
2.a) should appear the Get menu.
2.b) click on "Get" Menu
Result: In "User A" Browser should appear a web notification and a confirmation prompt with this message "User B is calling you to join in Room X"

add webnotification to ask user to join in room

---

public/css/office.css
public/js/office.web.js
views/office.ejs

Firefox don't display correct iframe height.
Improved iframe style to handle responsive height with firefox and chrome.
Before:
After:

Fix firefox responsive iframe

---

frontend/office.js
test/frontend/profile.test.js

This PR improves the test coverage of profile.js from 55% to 100%
run `npm test`
Code coverage of profile.js now is 100%

improve profile.js test from 55% to 100%

---

SETUP.md
app.json

fix: documentation to edit ROOMS_DATA environmen

---

public/css/office.css

resize the room size from 300px to 280px
run office and the room size now is 280px x 280px
show 4 rooms per line

resize the room size from 300px to 280px

---

.circleci/config.yml
package.json

WIP add test coverage report

---

Dockerfile

This reverts commit 8f112d965eeff71103c5d2244a9f6a408f6ba942.

Revert "dockerfile altered"

---

backend/app.server.js

This PR is an MVP to enable #matrix to have temporary rooms. 
Access `http://localhost:8080/new?roomId=xxxxxx&roomName=my-new-room`
The temporary room will be created and you will redirect to the new temporary room
Access `http://localhost:8080/remove?roomId=xxxxxx`
The temporary room will be deleted and you will redirect to the lounge room

add hability to create a temporary room

---

backend/office.socket.js
test/office.socket.test.js

Avoid server crash on connect to socket with an invalid user.
```
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at Array.<anonymous> (/var/app/dist/office.socket.js:32:28)
at run (/var/app/node_modules/socket.io/lib/namespace.js:124:11)
at Namespace.run (/var/app/node_modules/socket.io/lib/namespace.js:136:3)
at Namespace.add (/var/app/node_modules/socket.io/lib/namespace.js:164:8)
at Client.doConnect (/var/app/node_modules/socket.io/lib/client.js:97:20)
at Client.connect (/var/app/node_modules/socket.io/lib/client.js:66:17)
at Server.onconnection (/var/app/node_modules/socket.io/lib/index.js:435:10)
at Server.emit (events.js:189:13)
at Server.handshake (/var/app/node_modules/engine.io/lib/server.js:338:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! …
```

Fix error when socket io connection fails

---

frontend/components/RoomCard.js
frontend/office-events.js
frontend/office.js
package-lock.json

when there is **"="** in the user avatar URL is not possible to connect this user. 
Execute login with users with **"="** in avatar URL
this user can have a successful connect in the matrix office

fix avatar url encode

---

frontend/morpheus/hooks/useEvents.js

Remove "the" from room entry notification

---

README.md

A simple fix typo 
Using a markdown tool, like https://stackedit.io/

fix typo url

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/ConfirmDialog.js
frontend/src/components/MenuAuth.js
frontend/src/morpheus/App.js
frontend/src/morpheus/containers/ConfirmLogoutDialog.js
frontend/src/morpheus/containers/OfficeAppBar.js
frontend/src/morpheus/socket.js
frontend/src/morpheus/store/actions.js
frontend/src/morpheus/store/reducers.js
frontend/src/morpheus/store/selectors.js

Add missing logout feature to Morpheus Layout.
When logout in Morpheus, the app must:

Morpheus logout

---

frontend/src/profile.js
frontend/test/profile.test.js

This PR fix #190 
1. Enter in Matrix
2. Log in
3. Open local storage, remove `name` from the JSON of `user` key.
4. Update the page, the Matrix must regenerate from system failure.

Vikings fix user local storage validation

---

Dockerfile
frontend/package-lock.json

When you try to run `docker-compose up` the console is showing the error reported in this issue: https://github.com/ResultadosDigitais/matrix/issues/198
on console run `docker-compose up` 
```
juliemar.berri@rd001905-latitude3480:~/projects/matrix$ docker-compose up
Starting matrix_web_1 ... done
Attaching to matrix_web_1
web_1  | 
web_1  | > matrix@ start-backend /var/app
web_1  | > lerna run start-backend --stream
web_1  | 
web_1  | lerna notice cli v3.16.4
web_1  | lerna info Executing command in 1 package: "npm run start-backend"
web_1  | matrix-backend: > matrix-backend@ start-backend /var/app/backend
web_1  | matrix-backend: > NODE_ENV=production node ./dist/index.js
web_1  | matrix-backend: Running on http://0.0.0.0:8080
web_1  | matrix-backend: [ { id: …
```

Fix:198 Cannot find module on docker-compose

---

README.md
app.json

Add deploy to GCP button
Click in deploy to  GCP button
You have to be redirected to the GCP and a google console needs to start a deploy process

Add gcp button

---

README.md
app.json

Add a GCP deploy button 
Click in the GCP deploy Button
The application will be start to deploy in GCP Cloud RUN

uptade README.md with the GCP Deploy Button

---

README.md

Small fixes in environment variable topic in README.md:
- Changed topic name from "Environments" to "[Environment Variables](https://en.wikipedia.org/wiki/Environment_variable)". Environment is "production", "staging", "development", and the topic is about the variables;
- Changed the list from numbers to bullets, since there is no order in the definition of variables;
- Add missing Session variables;

Fix environment variable in README.md

---

frontend/src/notification.js

Correção que faltou no PR #252

New fix for Notification

---

README.md
docs/faq.md

Improvement in docs
Just read.
No English typos

Improve docs

---

docs/CHANGELOG.md

Add next version area to put changelog

add next release area in changelog file

---

backend/app/app.config.js

This piece of code could be replaced by a variable:
` 30 * 24 * 60 * 60 * 1000; // 30 days` 
To avoid problems with the "magic number" in the future.
My suggestion is to change comments by a variable. It is easier to read and understand.

refactor:[APPCONFIG] Refactoring magic number for variable

---

frontend/src/morpheus/Themes.js

Colors less saturated and less vibrated improve legibility and reduce visual vibration.
My suggestion is to change the colors current for less colors saturated and less vibrated. It's not the best, but it's a start.
Switch theme light/dark
Old colors:
[Print ](https://ibb.co/9YF96JZ)
New colors:
[Print ](https://ibb.co/8d0Sxcq)

style: [theme] less saturated colors in dark theme

---

frontend/src/locales/en/auth.json
frontend/src/locales/pt-br/auth.json
frontend/src/pages/login/logo/logo.js

It is an important attribute used specifies an alternate text for an image that cannot be displayed.
The project has the option switch language, so I took advantage of the opportunity to add the option at alt in English/Portuguese.
Switch language and logo inspect.
Check down:
[Version En](https://ibb.co/jbFN6rT)
[Version PT-BR](https://ibb.co/TkB1tS7)

The logo of the matrix was without the attribute alt. 

---

.circleci/config.yml
.gitignore
backend/package-lock.json
frontend/package-lock.json
package-lock.json

🔧 Update CI

---

catalog-info.yaml

**Contexto**
Estamos mapeando os componentes para dentro do Backstage e por isso precisamos deste arquivo yaml no mesmo diretório do componente para que ele seja refletido no Backstage.

add catalog info
