ResultadosDigitais/matrix

Dockerfile, README.md, docker-compose.yml, docker-entrypoint.sh
Using docker-compose to start the application in local environment just with `docker-compose up`.
Changing `node:8` to `node:8-alpine`, this reduces the time to build the image.
With `node:8`: 6 minutes and 14 seconds
With `node:8-alpine`: 46 seconds
=> Add docker compose and using node alpine version

controllers/office.controller.js, office.server.js, public/office.web.js
In this pull request, I fixed the problem when one user enters a room and all users receive the notification about all other users connected.  For example: we have 3 users connected. for convenience when the fifth user enter in room for synchronize him office we loop all connected users and send the event enter-room. After we implemented the web notification. all users receive repetited notification. this pull request solve this problem. because now we send only the sync room for last connected user.
=> fix the broadcast to sync room for current logged user

public/js/office.web.js
Fix #132
This PR main intent is to enable title with the user name to be shown when the user is in the meeting.
More details of how to reproduce could be found in issue #132.
=> Show user name as title when user is in a meeting

frontend/office.js
This PR fixes the get menu
Execute right click on the user avatar.
should appear the "get menu"
=> fix get menu using webpack

app.server.js, views/office.ejs
This PR concatenate the hostname + room-id to prevent room id conflict with other environments. We have two environments when the room-id is "room-1" when they enter in the Jitisi meet they will enter in the same meet.   
Create two environments using the default room-id
Expected that room-id is concatenated with domain name:
http://maydomain.com/office#**mydomain.com**-ac2b235a-b1e2-4848-a687-6669a3f7551b
=> Prevent meet conflict

app.server.js, frontend/office.js
##Description
This PR concatenate the hostname + room-id to prevent room id conflict with other environments. We have two environments when the room-id is "room-1" when they enter in the Jitisi meet they will enter in the same meet.
##How to test?
Create two environments using the default room-id
##Expected behavior
when you enter in meet the jitsi meet id needs to be **room-id + domain**
=> revert the md5 strategy and concat host only on vedeo meet

app.server.js
Description
When the client is in production with HTTPS and access the matrix in HTTP the users receive google login error. This PR enables to define the Environment Variable with the correct production protocol
How to test?
Folow the this steps: #142
Expected behavior
If the environment variable is defined https and the user access http we will redirect him to https
=> fix redirect http when we have a reverse proxy

backend/app.server.js, backend/controllers/assets.controller.js, package-lock.json, package.json, test/app.server.test.js, views/index.ejs, views/office.ejs, webpack.common.js
Browser can cache assets and users may not receive updates.
- Bundle assets with content hash at file name. (https://webpack.js.org/guides/caching/);
- Generate a manifest file for bundled assets;
- Use manifest to resolve assets name;
In development mode, the manifest file is read always, while in production mode, the manifest is read once.
=> Assets cache invalidation

backend/app.server.js, package-lock.json, views/office.ejs
Provide the ability to set a custom CSS with the environment variable  
Set environment variable `CUSTOM_STYLE` with a custom CSS like `body{background-image: url('https://image.freepik.com/vetores-gratis/festa-junina-bandeiras-decoracao-fundo_1017-18260.jpg');}`
Custom CSS will be applied and in the example case the background will appear festa junina
=> add hability to customize css

views/office.ejs
Style tag has an extra `>` char.
=> Fix broken tag

backend/app/app.routes.js, frontend/src/office.js
when you create a room with the route http://localhost:8080/new?roomId=xxxxxx&roomName=aaaaa and you are using the legacy theme, when you would try to enter in meeting in this new room, nothing happen.
1. I changed the redirect from legacy theme to the new Morpheus room meeting theme
2. I fixed in the legacy theme for entering in meeting in the new rooms 
create a new room with this route: http://localhost:8080/new?roomId=xxxxxx&roomName=aaaaa
=> Redirect new room to mortheus

frontend/src/morpheus/containers/OfficePage.js, frontend/src/morpheus/store/reducers.js, frontend/test/morpheus/store/reducers.test.js
We have been problems with Jitsi. And we are trying to test the experience of using an external meeting provider.  
add **externalMeetUrl** attribute with a Unique meet URL of your preferred meeting provider.
```
{ 
"id":"dc668138-37ee-4c6a-9d26-2d646c4d70ea",
"name":"Zion 2",
"externalMeetUrl":"https://myexternalmeetprovideruniqueurl"
}
```
when you click in "Enter Meet" #matrix will open the external meet in a tab.
=> add support to open external meeting in morpheus layout

frontend/src/morpheus/containers/OfficePage.js
The implementation of the external meet is not showing the Headphones decorator when the user enter in the meet.  
Create a room with *externalMeetUrl* param and enter in meet of this room
the user avatar needs to show headphones
=> Open external meet needs to show headphone decorator

README.md
In this PR we put more information about `externalMeetUrl` parameter, to help people to use other video conferences providers
Verify if the English needs to be fixed and if all images are appearing
An understandable README.md for all people.
=> Add externalMeetUrl docs

docker-compose.yml
Was not possible run project using docker-compose up immediately after clone project.
After clone project, execute the below command:
```
docker-compose up
```
Start the project.
=> fix error start project with docker-compose

backend/app/app.healthcheck.js, backend/app/index.js, backend/package-lock.json, backend/package.json, backend/test/app.healthcheck.test.js
Add a new endpoint to be used for health check. I used terminus because it provide a lot of util stuffs like graceful shutdown (it'll be important when we work on high availability for matrix)
Make the following curl:
```console
➜  Charts (camais-rooms) ✔ curl -i http://localhost:8080/healthz
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 17 Mar 2020 17:41:08 GMT
Connection: keep-alive
Content-Length: 15
{"status":"ok"}
```
or accessing via browser:
Have an endpoint to use as healthcheck. It's important to have to check liveness and readiness in Kubernetes, or a load balancer status check, for example.
=> Add healthcheck

.gitignore, docker-compose.yml
- Adding example file env vars to docker-compose.
- For security, ignoring any .env at gitignore.
Just add any .env file and check that will be ignored to commit.
After add file variables.env to root of project will be possible add env vars easily to start the project, like GOOGLE_CREDENTIAL and ROOMS env variables.
Example variables.env
```
GOOGLE_CREDENTIAL=XXXXXX.googleusercontent.com
#ENFORCE_SSL=false
ROOMS_SOURCE=ENVIRONMENT
ROOMS_DATA=[{"id":"17755865-e0a6-4809-b389-eeff5590fd3d","name":"ValarDohaeris"},{"id":"490693fb-1751-498a-a23a-3785e677530c","name":"Osiris"},{"id":"da5eef6b-9e0c-4c32-81eb-17596114bf5b","name":"Icarus"},{"id":"e8ed1b89-afa9-469f-8108-e527b51c76a1","name":"Caduceus"},{"id":"bab0452c-bbfa-4365-b263-6aa9d26d8e33","name":"Brahma"},{"id":"706e8018-8e4e-40a2-a433-975 …
```
=> Env var docker compose

README.md, app.json, frontend/src/jitsi/JitsiConfig.js
In the jitsi.org documentation, they explain to not hide jitsi.org logo when you are running embedded jitsi. We made a mistake hide the logo and this PR fix. @jitsi forgive us for the hesitation.  
Enter in a meeting 
The jitsi.org logo has to be present.
=> Fix jitsi logo

LICENSE
I think the LICENSE file was removed and GitHub does not understand anymore.
I recreated the MIT license file.
Reference: https://github.com/ResultadosDigitais/matrix/community
Kudos @felipecdo
=> Add a license file that github understant

frontend/src/components/NotificationCheckbox.js, frontend/src/notification.js
@tchiarato reportou o seguinte erro no iOS:
Olhando a documentação do Notification no MDN vi que o Safari no iOS não tem suporte: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API#Browser_compatibility
=> Ajusta a notificação para navegadores que não possui suporte

README.md, docs/faq.md
Update README to a better usability. 
- Add Table of Contents
- Reorganize sections and names
- Add Get in Touch section
- Add FAQ section
Just read. 
No English typos and full understanding from the readme
=> Improve Readme

README.md, docs/kubernetes/deployment.yaml, docs/kubernetes/service.yaml
Added instructions to README and Kubernetes example files
to docs folder.
Following issue #269 request, I added a nice configuration to run **#matrix** in Kubernetes and using a configmap to map the rooms.json file to the project instead of using environment variables.
Following the instructions in the README should end with a working version of **#matrix** in Kubernetes
Users are able to launch their own #matrix on their clusters without issues
=> Added Kubernetes instructions to docs

README.md
When we created the **Google Cloud Run Button** There was an incompatibility between `app.json` for Heroku and GCP. 
We reported this problem to google in [this issue](https://github.com/GoogleCloudPlatform/cloud-run-button/issues/112) and they fixed ignoring the `stack` field in [this commit](https://github.com/GoogleCloudPlatform/cloud-run-button/commit/1c284503067b12b0186d3a5d1fbc462494cd3f80) 
Execute installation with **Google 8Cloud Run Button**  
everything needs to work well and [this](https://github.com/GoogleCloudPlatform/cloud-run-button/issues/112#issuecomment-602226502) problem have to be fixed.
=> remove GCP exclusive button branch

variables.example.env
Added missing `variables` at `variables.example.env`. Without that, docker-compose does not runs matrix 😢 .
=> Add ROOMS_DATA and ROOMS_SOURCE at variables.env.example

README.md
Currently the link regarding the creation of Google Api credentials in "Instalation / Environment Variables" in the README.md file is redirecting the user directly to https://developers.google.com/identity/sign-in/web/sign-in instead of our step by step. 
This PR updates the link to /docs/GOOGLE-CREDENTIAL-STEP-BY-STEP.md :smile:
=> Update google api reference link at README.md

docker-images/matrix-dev/Dockerfile
To facilitate the development and testing of new features, I restructured the DEV Dockerfile. With this, the download of dependencies will be cached (as long as the package.json file is not changed) and at the end, the tests are executed.
Copy the content of the Dockerfile (docker-images\matrix-dev) to the root Dockerfile.
After change something in the sourcecode, the build process will skip the "npm install --ignore-scripts" layer.
This procedure increases the final size and layer numbers of the image. As much as the increase is not impressive, it is important not to use this Dockerfile in production.
=> Add a cache layer to npm install and run tests

README.md, backend/app/app.config.js, backend/app/services/auth/authorization.js, backend/app/services/auth/authorization.test.js, backend/app/services/auth/index.js, docs/CHANGELOG.md
Considering the use case where a deploy can only be accessed by members of a project, however the use of a secure domain is not possible. This PR adds an authorization method where only a list of users can login. Still maintaining authentication with Google Auth.
Add the WHITELIST_USERS Env variable with an array of e-mails (WHITELIST_USERS=["teste@gmail.com", "teste2@gmail.com"]). Try to login with a google account.
If the user have their email listed, login. If not, log that him is not authorized.
=> Add a user list method of authorization

frontend/src/morpheus/store/reducers.js, frontend/test/morpheus/store/reducers.test.js
Resolves #343 
1. Have a user or room with an accent somewhere in the name (eg: José/Café)
2. Search for their name without including an accent (jose)
User should show up even if the search query doesn't include the accent.
=> #343 ignore accents in search
